name: First Workflow 
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-20.04
    steps:
        - name: echo a string 
          run: echo "Hello Github Actions"
        - name: Multiline Command
          run: |
            node -v
            npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view SW Version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands 
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Setup
        run: doesnotexists