name: First Workflow 
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-20.04
    steps:
        - name: echo a string 
          run: echo "Hello Github Actions"
        - name: Multiline Command
          run: |
            node -v
            npm -v
            